services:
  backend:
    build: .
    container_name: clubsheet-backend:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:dede@postgres:5432/clubsheet-db?schema=build
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: clubsheet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clubsheet
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: